config/routes.rb
Rails.application.routes.draw do
  resources :coberturas
  resources :apolices
  resources :aditivos
  resources :propostas
  root 'static#home'
  #root 'apolices#home'
  get 'apolices/relatorio'
  get "/relatorio", to: "apolices#relatorio", as: :relatorio
  get "/relatorionovo", to: "apolices#relatorionovo", as: :relatorionovo


  get "/showproposta", to: "propostas#showproposta", as: :showproposta


  get "/relatorioproposta", to: "propostas#relatorio_proposta", as: :relatorioproposta

  get "/visualizarproposta", to: "propostas#relatorio_proposta_html", as: :visualizarproposta
  get "/aceitarProposta", to: "propostas#aceitarProposta", as: :aceitarProposta

  get "/relatorioaditivo", to: "aditivos#relatorio", as: :relatorioaditivo

  get "/home", to: "static#home", as: :home

  match '/addservico', to: 'apolices#add_servico', via: 'get'
  match '/buscaservico', to: 'apolices#busca_servico', via: 'get'
  match '/deletaservico', to: 'apolices#deleta_servico', via: 'get'
  match '/coberturas_apolice', to: 'apolices#coberturas_apolice', via: 'get'
  match '/alteracobertura', to: 'apolices#alterar_cobertura', via: 'get'
  match '/deletecobertura', to: 'apolices#delete_cobertura', via: 'get'
  match '/addcobertura', to: 'apolices#add_cobertura', via: 'get'


end

app/models/apolice.rb
class Apolice < ActiveRecord::Base

 has_many :coberturaapolices, dependent: :destroy
 has_many :servicos, dependent: :destroy

 def self.search(term, condominio, apartamento_id = 0)
      sql = sql + "lower(pe.cpf) like '%#{term.downcase}%' AND "
     self.joins(sql)
 end

end

app/controllers/apolices_controller.rb
class ApolicesController < ApplicationController
  before_action :set_apolice, only: [:show, :edit, :update, :destroy]


  include ActionView::Helpers::NumberHelper

 def coberturas_apolice
     @coberturas = Coberturaapolice.where(apolice_id: params[:apolice_id])
     render :json => @coberturas.map { |item| {:id => item.id, 
                                                :nome => item.cobertura.nome, 
                                                :valor => number_to_currency(item.valor, unit: "R$", separator: ",", delimiter: "."),
                                                :valor_franquia =>number_to_currency(item.valor_franquia, unit: "R$", separator: ",", delimiter: ".") }}
 end

 def alterar_cobertura

     params[:valor] = params[:valor].gsub("R$", '')
     params[:valor] = params[:valor].gsub(".", '')
     params[:valor] = params[:valor].gsub(",", '.')

     params[:valor_franquia] = params[:valor_franquia].gsub("R$", '')
     params[:valor_franquia] = params[:valor_franquia].gsub(".", '')
     params[:valor_franquia] = params[:valor_franquia].gsub(",", '.')

     @cobertura = Coberturaapolice.find(params[:id])
     @cobertura.valor = params[:valor]
     @cobertura.valor_franquia = params[:valor_franquia]
     @cobertura.save
     render :json => true
 end


 def delete_cobertura
  @cobertura = Coberturaapolice.find(params[:id])
  @cobertura.destroy
  render :json => true
 end


 def home
 end

 def add_servico
   @servico = Servico.new
   @servico.nome = params[:servico]
   @servico.apolice_id = params[:apolice_id]
   @servico.save
   render :json => true
 end


 def add_cobertura

  @coberturaapolice = Coberturaapolice.new 
  @cobertura = Cobertura.find(params[:cobertura_id])
  @coberturaapolice.cobertura_id = @cobertura.id
  @coberturaapolice.valor = @cobertura.valor
  @coberturaapolice.valor_franquia = @cobertura.valor_franquia
  @coberturaapolice.apolice_id = params[:apolice_id]
  @coberturaapolice.save

  render :json => true
end


def busca_servico
  @servico = Servico.where(apolice_id: params[:apolice_id])

  render :json => @servico.map { |item| {:id => item.id, :nome => item.nome }}
end

def deleta_servico
  @servico = Servico.find(params[:servico_id])
  @servico.destroy
  render :json => true
end


def relatorio
  
     @apolice = Apolice.find(params[:id])
  
     respond_to do |format|
       format.html
       format.pdf { render pdf: "reserva"
        # footer: { center: "[page] de [topage]" }
         }
     end
end

def relatorionovo

   @apolice = Apolice.find(params[:id])

   respond_to do |format|
     format.html
     format.pdf { render pdf: "reserva"
      # footer: { center: "[page] de [topage]" }
       }
   end
 end

  # GET /apolices
  # GET /apolices.json
  def index
    if params[:q]
      @q =  params[:q].downcase
      @apolices = Apolice.where("page IS NULL and lower(nome_segurado) like '%#{@q}%' OR lower(apartamento) like '%#{@q}%'").page(params[:page]).per(10).order("id DESC")
    else
      @apolices = Apolice.where("page IS NULL and (ramo IS NOT NULL and produto IS NOT NULL and apolice IS NOT NULL)").page(params[:page]).per(10).order("id DESC")
    end
  end

  # GET /apolices/1
  # GET /apolices/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf { render pdf: "Apolice",
        header: {center: "lllL"},
        footer: { center: "[page] de [topage]" }
        }
    end
  end

  # GET /apolices/new
  def new
    
    @apolice = Apolice.new                                                                                                           
    if !params[:id].blank?
       apolice = Apolice.find(params[:id])
       
       @apolice.ramo = apolice.ramo
       @apolice.produto = apolice.produto
       @apolice.apolice = apolice.apolice
       @apolice.item = apolice.item
       @apolice.data_proposta = apolice.data_proposta
       @apolice.vig_inicio = apolice.vig_inicio
       @apolice.vig_termino = apolice.vig_termino
       @apolice.nome_segurado = apolice.nome_segurado
       @apolice.cpf = apolice.cpf
       @apolice.endereco = apolice.endereco
       @apolice.bairro = apolice.bairro
       @apolice.cidade = apolice.cidade
       @apolice.cep = apolice.cep
       @apolice.uf = apolice.uf
       @apolice.valr_adicional = apolice.valr_adicional
       @apolice.valr_custo = apolice.valr_custo
       @apolice.valr_iof = apolice.valr_iof
       @apolice.valr_premiototal = apolice.valr_premiototal
       @apolice.desc_obs = apolice.desc_obs
       @apolice.numr_mensal = apolice.numr_mensal
       @apolice.cnpj = apolice.cnpj
       @apolice.apartamento = apolice.apartamento
       @apolice.valor_franquiaportao = apolice.valor_franquiaportao
       @apolice.valor_mensal = apolice.valor_mensal
       @apolice.qtd_parcelas = apolice.qtd_parcelas
       @apolice.data_proposta = apolice.data_proposta
     end
    
       respond_to do |format|
       if @apolice.save
           coberturas = Cobertura.all
         
           coberturas.each do |item|
             coberturaapolice = Coberturaapolice.new
             coberturaapolice.apolice_id = @apolice.id
             coberturaapolice.cobertura_id = item.id
             coberturaapolice.valor = item.valor
             coberturaapolice.valor_franquia = item.valor_franquia
             coberturaapolice.save
           end 
           format.html { redirect_to edit_apolice_path(@apolice), notice: 'Cadastro realizado com sucesso.' }
           format.json { render :show, status: :created, location: @apolice }
         else
           format.html { render :new }
           format.json { render json: @apolice.errors, status: :unprocessable_entity }
         end
       end
  end

  # GET /apolices/1/edit
  def edit

     @apolice.data_proposta = @apolice.data_proposta.strftime("%d/%m/%Y") rescue nil
     @apolice.vig_inicio = @apolice.vig_inicio.strftime("%d/%m/%Y") rescue nil
     @apolice.vig_termino = @apolice.vig_termino.strftime("%d/%m/%Y") rescue nil

  end

  # POST /apolices
  # POST /apolices.json
  def create
    @apolice = Apolice.new(apolice_params)

    respond_to do |format|
      if @apolice.save

        if @apolice.page == "aditivo"
          format.html { redirect_to aditivos_path, notice: 'Cadastro realizado com sucesso.' }
          format.json { render :show, status: :created, location: @apolice }
        else
          format.html { redirect_to @apolice, notice: 'Cadastro realizado com sucesso.' }
          format.json { render :show, status: :created, location: @apolice }
        end

      
      else
        format.html { render :new }
        format.json { render json: @apolice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apolices/1
  # PATCH/PUT /apolices/1.json
  def update
    respond_to do |format|
      if @apolice.update(apolice_params)

        if @apolice.page == "aditivo"
          format.html { redirect_to aditivos_path, notice: 'Registro alterado com sucesso.' }
          format.json { render :show, status: :ok, location: @apolice }      
        else
          format.html { redirect_to @apolice, notice: 'Registro alterado com sucesso.' }
          format.json { render :show, status: :ok, location: @apolice }  
        end
      else

        if @apolice.page == "aditivo"
          format.html { render :edit }
          format.json { render json: @apolice.errors, status: :unprocessable_entity }   
        else
          format.html { render :edit }
          format.json { render json: @apolice.errors, status: :unprocessable_entity }
        end     
      end
    end
  end

  # DELETE /apolices/1
  # DELETE /apolices/1.json
  def destroy
    @apolice.destroy
    respond_to do |format|
      format.html { redirect_to apolices_url, notice: 'Registro deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apolice
      @apolice = Apolice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apolice_params
      params.require(:apolice).permit(:ramo, :produto, :apolice, :item, :data_proposta, :vig_inicio, :vig_termino, :nome_segurado, :cpf, :endereco, :cidade, :bairro, :cep, :uf, :valr_premioliquido, :valr_adicional, :valr_custo, :valr_iof, :valr_premiototal, :desc_obs, :numr_mensal, :cnpj, :apartamento, :page, :valor_franquiaportao, :valor_mensal, :qtd_parcelas, :data_propostaaceita)
    end
end

app/helpers/apolices_helper.rb
module ApolicesHelper
end

app/views/apolices/_form.html.erb
<%= form_for(@apolice) do |f| %>
  <% if @apolice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apolice.errors.count, "error") %> prohibited this apolice from being saved:</h2>

      <ul>
      <% @apolice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-lg-3">
     <%= f.label :ramo %><br>
     <%= f.text_field :ramo, :class => "form-control" %>
   </div>
  <div class="col-lg-3">
    <%= f.label :produto %><br>
    <%= f.text_field :produto, :class => "form-control"%>
   </div>
    <div class="col-lg-3">
      <%= f.label :apolice %><br>
      <%= f.text_field :apolice, :class => "form-control"%>
    </div>
    <div class="col-lg-3">
      <%= f.label :item %><br>
      <%= f.text_field :item, :class => "form-control" %>
    </div>
  </div>

<div class="row">
  <div class="col-lg-2">
    <%= f.label :data_proposta %><br>
    <%= f.text_field :data_proposta, :class => "form-control"  %>
  </div>
  <div class="col-lg-2">
    <%= f.label :vig_inicio %><br>
    <%= f.text_field :vig_inicio, :class => "form-control"  %>
  </div>
  <div class="col-lg-2">
    <%= f.label :vig_termino %><br>
    <%= f.text_field :vig_termino, :class => "form-control"  %>
  </div>
  <div class="col-lg-2">
   <label>N° Sorteio Mensal</label>
    <%= f.text_field :numr_mensal, :class => "form-control"  %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= f.label :nome_segurado %><br>
    <%= f.text_field :nome_segurado, :class => "form-control"  %>

  </div>
  <div class="col-lg-1">
    <div class="radio">
     <label><input type="radio" onclick="selecionar('CPF')" id="radiocpf" checked name="optradio">CPF</label>
    </div>
    <div class="radio">
     <label><input type="radio" onclick="selecionar('CNPJ')" id="radiocnpj" name="optradio">CNPJ</label>
    </div>
    <%= f.hidden_field :cnpj %>
 </div>
  <div class="col-lg-3">
   <label id="cpf">CPF</label>
   <label id="cnpj">CNPJ</label>
    <%= f.text_field :cpf, :class => "form-control"  %>
  </div>
</div>
<div class="row">
  <div class="col-lg-7">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco, :class => "form-control" %>
  </div>
  <div class="col-lg-2">
    <%= f.label :apartamento %><br>
    <%= f.text_field :apartamento, :class => "form-control" %>
  </div>
  <div class="col-lg-3">
    <%= f.label :bairro %><br>
    <%= f.text_field :bairro, :class => "form-control" %>
  </div>
</div>
<div class="row">
  <div class="col-lg-4">
    <%= f.label :cidade %><br>
    <%= f.text_field :cidade, :class => "form-control" %>
  </div>
  <div class="col-lg-2">
    <label>CEP</label>
    <%= f.text_field :cep, :class => "form-control" %>
  </div>
  <div class="col-lg-2">
    <label>UF</label>
    <%= f.text_field :uf, :class => "form-control" %>
  </div>
</div>

<div class="row">
  <div class="col-lg-2">
    <label>Prêmio líquido</label>
    <%= f.text_field :valr_premioliquido, :class => "form-control" %>
  </div>
  <div class="col-lg-2">
    <label>Sonar Assistencia</label>
    <%= f.text_field :valr_adicional, :class => "form-control" %>
  </div>

  <div class="col-lg-2">
    <label>Ad. de Fracionamento</label>
    <%= f.text_field :valr_custo, :class => "form-control" %>
  </div>
  <div class="col-lg-2">
    <label>IOF</label>
    <%= f.text_field :valr_iof, :class => "form-control" %>
  </div>
  <div class="col-lg-2">
    <label>Prêmio Total</label>
    <%= f.text_field :valr_premiototal, :class => "form-control" %>
  </div>
</div>

  <div class="row">
    <div class="col-lg-12">
      <label>Observações</label>
      <%= f.text_area :desc_obs, :class => "form-control" %>
    </div>
  </div>

  <hr>

  <%if @apolice.id%>
  <div class="row">
    <div class="col-lg-10">
      <select class="form-control" name="servico" id="servico">
        <option value="Chaveiro">Chaveiro</option>
        <option value="Hidráulica">Hidráulica</option>
        <option value="Eletrícista">Eletrícista</option>
        <option value="Vidraceiro">Vidraceiro</option>
        <option value="Desentupimento">Desentupimento</option>
        <option value="Chuveiro">Chuveiro</option>
        <option value="Linha Branca">Linha Branca</option>
        <option value="RC-Familiar">RC-Familiar</option>
      </select>
    </div>
    <div class="col-lg-2">
      <button type="button" class="btn btn-default" onclick="salva()">
        <span class="glyphicon glyphicon-arrow-down text-primary"></span> Adicionar
         </button>
    </div>
  </div>

  <br>
  <table class="table table-bordered">
      <thead>
        <tr>
          <th>Serviços utilizados</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="tbservico">
      </tbody>
    </table>

  <hr>

  <div class="row">
    <div class="col-lg-10">
      <select class="form-control" name="cobertura" id="cobertura">
        <% Cobertura.all.each do |item| %>
          <option value="<%=item.id%>"><%=item.nome%></option>
        <%end%>
      </select>
    </div>
    <div class="col-lg-2">
      <button type="button" class="btn btn-default" onclick="addCobertura()">
        <span class="glyphicon glyphicon-arrow-down text-primary"></span> Adicionar
         </button>
    </div>
  </div>


   <div class="panel panel-default">
    <div class="panel-heading">Coberturas</div>
    <div class="panel-body">
        
        <table class="table table-bordered">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Valor</th>
          <th>Franquia</th>
          <th></th>
        </tr>
      </thead>
       <tbody id="tbcoberturas">
       </tbody>
    </table>

     </div>
    </div>

    </div>
   </div>

 <% end %>

<div class="row mar-bot40">
<div class="col-lg-8" >
 <div class="btn-group">
    <button type="submit" value="Submit" class="btn btn-primary btn-sm">
    <span class="glyphicon glyphicon-floppy-disk"></span> Salvar
    </button>
    <%= link_to apolices_path, :class => "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-arrow-left"></span> Voltar
      <% end %>
  </div>
  </div>
 </div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">

    <input type="hidden" name="cobertura_id" id="cobertura_id">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Alterar Cobertura</h4>
      </div>
      <div class="modal-body">
       <div class="row">
         <div class='col-lg-12'>
           Valor 
            <input type='text' id='valor' name='valor' class='form-control'>
         </div>
        </div>
        <div class="row">
        <br>
        <div class='col-lg-12'>
           Valor franquia
           <input type='text' id='valor_franquia' name='valor_franquia' class='form-control'>
        </div>
       </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" onclick="salvaCobertura()" data-dismiss="modal">Salvar</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
    </div>

  </div>
</div>


 <% end %>

<script type="text/javascript">
function modalCobertura(item){
  
  $("#cobertura_id").val(item.id);
  $("#valor").val(item.valor);
  $("#valor_franquia").val(item.valor_franquia);
  $("#myModal").modal()
}
//função salvar/editar dados despesas
 function salva(){
      $.ajax({
        url: '/addservico',
        data : {
            servico:  $('#servico').val(),
            apolice_id: '<%=@apolice.id%>'
        },
        success: function(data){
          buscaServicos();
        }
      })
  };
 function addCobertura(){
      $.ajax({
        url: '/addcobertura',
        data : {
            cobertura_id:  $('#cobertura').val(),
            apolice_id: '<%=@apolice.id%>'
        },
        success: function(data){
          buscaCoberturas();
        }
      })
  };
function buscaServicos() {
  $.ajax({
    url: '/buscaservico',
    data : {
        apolice_id: '<%=@apolice.id%>'
    },
    success: function(data){
          var html = "";
          $("#tbservico").empty();
           for (var i in data) {
             var item = data[i];
             html += "<tr><td>"+item.nome+"</td>";
             html += "<td Align='center'>";
             html += " <button type='button' onclick='deleta_servico("+item.id+")' data-toggle='tooltip' title='Excluir' class='btn btn-danger btn-xs' aria-label='Left Align'>";
             html += "  <span class='glyphicon glyphicon-trash' aria-hidden='true'></span></button></tr>";
           };
           $("#tbservico").append(html);
         }
     })
  }
  //função salvar/editar dados despesas
function deleta_servico(id){
        $.ajax({
          url: '/deletaservico',
          data : {
              servico_id:  id
          },
          success: function(data){
            buscaServicos();
          }
        })
  };
http://localhost:3000/coberturas_apolice?apolice_id=16
function buscaCoberturas() {
  $.ajax({
    url: '/coberturas_apolice',
    data : {
      apolice_id: '<%=@apolice.id%>'
    },
    success: function(data){
          var html = "";
          $("#tbcoberturas").empty();
           for (var i in data) {
             var item = data[i];
             console.log(i);
             if(item != null){
              html += "<tr><td>"+item.nome+"</td>";
              html += "<td>"+item.valor+"</td>";
              html += "<td>"+item.valor_franquia+"</td>";
              html += "<td Align='center'>";
              html += " <button type='button' onclick='modalCobertura("+JSON.stringify(item)+")' data-toggle='tooltip' title='Excluir' class='btn btn-primary btn-xs' aria-label='Left Align'>";
              html += " <span class='glyphicon glyphicon-pencil' aria-hidden='true'></span></button>";
              html += " <button type='button' onclick='delete_cobertura("+item.id+")' data-toggle='tooltip' title='Excluir' class='btn btn-danger btn-xs' aria-label='Left Align'>";
              html += "  <span class='glyphicon glyphicon-trash' aria-hidden='true'></span></button></td></tr>";
             
             }
             
           }; 
           $("#tbcoberturas").append(html);        
         }
     })
  }
function salvaCobertura(){
    $.ajax({
        url: '/alteracobertura',
        data : {
            id:  $("#cobertura_id").val(),
            valor: $("#valor").val(),
            valor_franquia: $("#valor_franquia").val(),
        },
        success: function(data){
          buscaCoberturas();
        }
   })
}
function delete_cobertura(id){
    $.ajax({
        url: '/deletecobertura',
        data : {
            id:  id
        },
        success: function(data){
          buscaCoberturas();
        }
   })
}
function selecionar(val) {
  if (val == "CPF"){
      $("#cpf").show();
      $("#cnpj").hide();
      $("#apolice_cnpj").val(false);
      $("#apolice_cpf").mask("999.999.999-99");
  }
  if (val == "CNPJ"){
      $("#cnpj").show();
      $("#cpf").hide();
      $("#apolice_cnpj").val(true);
      $("#apolice_cpf").mask("99.999.999/9999-99");
  }
}
jQuery(function($){
  $("#cnpj").hide();
  $("#apolice_data_proposta").mask("99/99/9999");
  $("#apolice_vig_inicio").mask("99/99/9999");
  $("#apolice_vig_termino").mask("99/99/9999");
  var x = $("#apolice_cnpj").val();
   if(x){
        $("#apolice_cpf").mask("99.999.999/9999-99");
          $("#radiocnpj").attr("checked",true);
          $("#apolice_cnpj").val(true);
     }else{
        $("#apolice_cpf").mask("999.999.999-99");
        $("#radiocpf").attr("checked",true);
        $("#apolice_cnpj").val(false);
    }
});
$(function() {
   $("#apolice_valr_premioliquido").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   $("#apolice_valr_adicional").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   $("#apolice_valr_custo").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   $("#apolice_valr_iof").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   $("#apolice_valr_premiototal").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
  
   $("#valor").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   $("#valor_franquia").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   
})
buscaServicos();
buscaCoberturas();
</script>

app/views/apolices/home.html.erb
<br>
<div class="panel panel-default">
  <div class="panel-body">
    <h1>....................Sistema temporariamente indisponível....................</h1>
  </div>
</div>

app/views/apolices/index.html.erb
<br>

<p id="notice"><%= notice %></p>

<%= form_tag nil, method: 'GET' do %>
  <div class="row">
    <div class="col-lg-12">
      <div class="input-group">
        <input id="q" name="q" type="text" value="<%=@q%>" class="form-control" placeholder="Pesquise pelo nome ou apartamento">
        <span class="input-group-btn">
          <button class="btn btn-success" type="submit" >Buscar</button>
        </span>
      </div>
    </div>
  </div>
  <br />

<% end %>
<div class="panel panel-default">
  <div class="panel-heading">Lista de apólices</div>
  <div class="panel-body">
    <table class="table table-hover table-condensed">
      <thead>
        <tr>

          <th>Nome segurado</th>
          <th>N° Apolice</th>
          <th>CPF</th>
          <th>Prêmio liquido</th>
          <th>Adicional</th>
          <th>Custo</th>
          <th>IOF</th>
          <th>Prêmio Total</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @apolices.each do |apolice| %>
          <tr>
            <td><%= apolice.nome_segurado %></td>
            <td><%= apolice.apolice %></td>
            <td><%= apolice.cpf %></td>
            <td><%= apolice.valr_premioliquido %></td>
            <td><%= apolice.valr_adicional %></td>
            <td><%= apolice.valr_custo %></td>
            <td><%= apolice.valr_iof %></td>
            <td><%= apolice.valr_premiototal %></td>
            <td align='right'>
              <div class="btn-group">
                 <%= link_to new_apolice_path(id: apolice.id), class: "btn btn-default btn-sm" do %>
                    <span class="glyphicon glyphicon-transfer text-primary"></span>
                  <% end %>
                  <%= link_to edit_apolice_path(apolice), class: "btn btn-default btn-sm" do %>
                    <span class="glyphicon glyphicon-pencil text-primary"></span> Editar
                  <% end %>
                 <%= link_to apolice, method: :delete, data: { confirm: 'Deseja excluir o registro?' }, class: "btn btn-default btn-sm" do %>
                    <span class="glyphicon glyphicon-trash text-danger"></span> Excluir
                  <% end %>
                  <%= link_to relatorio_path(id: apolice, format: :pdf), class: "btn btn-default btn-sm" do %>
                    <span class="glyphicon glyphicon-print"></span> 1°
                  <% end %>
                   <%= link_to relatorionovo_path(id: apolice, format: :pdf), class: "btn btn-default btn-sm" do %>
                    <span class="glyphicon glyphicon-print"></span> 2°
                  <% end %>
              </div>
             </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= paginate @apolices, :window => 2 %>

<br>
<%= link_to new_apolice_path, class: "btn btn-default btn-sm" do %>
       <span class="glyphicon glyphicon-file"></span>Novo
<% end %>

app/views/apolices/new.html.erb
<br>

<div class="panel panel-default">
  <div class="panel-heading">Cadastro de Apólice</div>
  <div class="panel-body">
     <%= render 'form' %>