config/routes.rb
Rails.application.routes.draw do
  resources :coberturas
  resources :apolices
  resources :aditivos
  resources :propostas
  root 'static#home'
  #root 'apolices#home'
  get 'apolices/relatorio'
  get "/relatorio", to: "apolices#relatorio", as: :relatorio
  get "/relatorionovo", to: "apolices#relatorionovo", as: :relatorionovo


  get "/showproposta", to: "propostas#showproposta", as: :showproposta


  get "/relatorioproposta", to: "propostas#relatorio_proposta", as: :relatorioproposta

  get "/visualizarproposta", to: "propostas#relatorio_proposta_html", as: :visualizarproposta
  get "/aceitarProposta", to: "propostas#aceitarProposta", as: :aceitarProposta

  get "/relatorioaditivo", to: "aditivos#relatorio", as: :relatorioaditivo

  get "/home", to: "static#home", as: :home

  match '/addservico', to: 'apolices#add_servico', via: 'get'
  match '/buscaservico', to: 'apolices#busca_servico', via: 'get'
  match '/deletaservico', to: 'apolices#deleta_servico', via: 'get'
  match '/coberturas_apolice', to: 'apolices#coberturas_apolice', via: 'get'
  match '/alteracobertura', to: 'apolices#alterar_cobertura', via: 'get'
  match '/deletecobertura', to: 'apolices#delete_cobertura', via: 'get'
  match '/addcobertura', to: 'apolices#add_cobertura', via: 'get'


end

app/models/cobertura.rb
class Cobertura < ActiveRecord::Base
end

app/controllers/coberturas_controller.rb
class CoberturasController < ApplicationController
  before_action :set_cobertura, only: [:show, :edit, :update, :destroy]

  # GET /coberturas
  # GET /coberturas.json
  def index
    @coberturas = Cobertura.all
  end

  # GET /coberturas/1
  # GET /coberturas/1.json
  def show
  end

  # GET /coberturas/new
  def new
    @cobertura = Cobertura.new
  end

  # GET /coberturas/1/edit
  def edit
  end

  # POST /coberturas
  # POST /coberturas.json
  def create
    @cobertura = Cobertura.new(cobertura_params)

    @apolice.page = "proposta"

    respond_to do |format|
      if @cobertura.save
        format.html { redirect_to @cobertura, notice: 'Cobertura was successfully created.' }
        format.json { render :show, status: :created, location: @cobertura }
      else
        format.html { render :new }
        format.json { render json: @cobertura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coberturas/1
  # PATCH/PUT /coberturas/1.json
  def update
    respond_to do |format|
      if @cobertura.update(cobertura_params)
        format.html { redirect_to @cobertura, notice: 'Cobertura was successfully updated.' }
        format.json { render :show, status: :ok, location: @cobertura }
      else
        format.html { render :edit }
        format.json { render json: @cobertura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coberturas/1
  # DELETE /coberturas/1.json
  def destroy
    @cobertura.destroy
    respond_to do |format|
      format.html { redirect_to coberturas_url, notice: 'Cobertura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cobertura
      @cobertura = Cobertura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cobertura_params
      params.require(:cobertura).permit(:nome, :valor, :valor_franquia)
    end
end

app/helpers/coberturas_helper.rb
module CoberturasHelper
end

app/views/coberturas/_form.html.erb
<%= form_for(@cobertura) do |f| %>
  <% if @cobertura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cobertura.errors.count, "error") %> prohibited this cobertura from being saved:</h2>

      <ul>
      <% @cobertura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :valor_franquia %><br>
    <%= f.text_field :valor_franquia %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coberturas/edit.html.erb
<h1>Editing Cobertura</h1>

<%= render 'form' %>

<%= link_to 'Show', @cobertura %> |
<%= link_to 'Back', coberturas_path %>

app/views/coberturas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Coberturas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Valor</th>
      <th>Valor franquia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coberturas.each do |cobertura| %>
      <tr>
        <td><%= cobertura.nome %></td>
        <td><%= cobertura.valor %></td>
        <td><%= cobertura.valor_franquia %></td>
        <td><%= link_to 'Show', cobertura %></td>
        <td><%= link_to 'Edit', edit_cobertura_path(cobertura) %></td>
        <td><%= link_to 'Destroy', cobertura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cobertura', new_cobertura_path %>

app/views/coberturas/new.html.erb
<h1>New Cobertura</h1>

<%= render 'form' %>

<%= link_to 'Back', coberturas_path %>

app/views/coberturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cobertura.nome %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @cobertura.valor %>
</p>

<p>
  <strong>Valor franquia:</strong>
  <%= @cobertura.valor_franquia %>
</p>

<%= link_to 'Edit', edit_cobertura_path(@cobertura) %> |
<%= link_to 'Back', coberturas_path %>