config/routes.rb
Rails.application.routes.draw do
  resources :coberturas
  resources :apolices
  resources :aditivos
  resources :propostas
  root 'static#home'
  #root 'apolices#home'
  get 'apolices/relatorio'
  get "/relatorio", to: "apolices#relatorio", as: :relatorio
  get "/relatorionovo", to: "apolices#relatorionovo", as: :relatorionovo


  get "/showproposta", to: "propostas#showproposta", as: :showproposta


  get "/relatorioproposta", to: "propostas#relatorio_proposta", as: :relatorioproposta

  get "/visualizarproposta", to: "propostas#relatorio_proposta_html", as: :visualizarproposta
  get "/aceitarProposta", to: "propostas#aceitarProposta", as: :aceitarProposta

  get "/relatorioaditivo", to: "aditivos#relatorio", as: :relatorioaditivo

  get "/home", to: "static#home", as: :home

  match '/addservico', to: 'apolices#add_servico', via: 'get'
  match '/buscaservico', to: 'apolices#busca_servico', via: 'get'
  match '/deletaservico', to: 'apolices#deleta_servico', via: 'get'
  match '/coberturas_apolice', to: 'apolices#coberturas_apolice', via: 'get'
  match '/alteracobertura', to: 'apolices#alterar_cobertura', via: 'get'
  match '/deletecobertura', to: 'apolices#delete_cobertura', via: 'get'
  match '/addcobertura', to: 'apolices#add_cobertura', via: 'get'


end

app/controllers/propostas_controller.rb
class PropostasController < ApplicationController
  before_action :set_apolice, only: [:show, :edit, :update, :destroy]

  
  def relatorio_proposta
    @apolice = Apolice.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf { render pdf: "reserva"
       # footer: { center: "[page] de [topage]" }
        }
    end
  end


def relatorio_proposta_html
  @apolice = Apolice.find(params[:id])
end


def aceitarProposta 
  @apolice = Apolice.find(params[:apolice_id])
  @apolice.flag_propostaaceita = true
  @apolice.data_propostaaceita = Time.now
  @apolice.save

  render :json => true

end 

  
  # GET /apolices
  # GET /apolices.json
  def index
      if params[:q]
          @q =  params[:q].downcase
          @apolices = Apolice.where("page = 'proposta' AND lower(nome_segurado) like '%#{@q}%' OR lower(apartamento) like '%#{@q}%'").page(params[:page]).per(10)
        else
          @apolices = Apolice.where("page = 'proposta'").page(params[:page]).per(10)
      end
  end

  # GET /apolices/new
  def new
  
    @apolice = Apolice.new                                                                                                           
    if !params[:id].blank?
       apolice = Apolice.find(params[:id])
       
       @apolice.ramo = apolice.ramo
       @apolice.produto = apolice.produto
       @apolice.apolice = apolice.apolice
       @apolice.item = apolice.item
       @apolice.data_proposta = apolice.data_proposta
       @apolice.vig_inicio = apolice.vig_inicio
       @apolice.vig_termino = apolice.vig_termino
       @apolice.nome_segurado = apolice.nome_segurado
       @apolice.cpf = apolice.cpf
       @apolice.endereco = apolice.endereco
       @apolice.bairro = apolice.bairro
       @apolice.cidade = apolice.cidade
       @apolice.cep = apolice.cep
       @apolice.uf = apolice.uf
       @apolice.valr_adicional = apolice.valr_adicional
       @apolice.valr_custo = apolice.valr_custo
       @apolice.valr_iof = apolice.valr_iof
       @apolice.valr_premiototal = apolice.valr_premiototal
       @apolice.desc_obs = apolice.desc_obs
       @apolice.numr_mensal = apolice.numr_mensal
       @apolice.cnpj = apolice.cnpj
       @apolice.apartamento = apolice.apartamento
       @apolice.page = "proposta"
       @apolice.valor_franquiaportao = apolice.valor_franquiaportao
       @apolice.valor_mensal = apolice.valor_mensal
       @apolice.qtd_parcelas = apolice.qtd_parcelas
       @apolice.data_proposta = apolice.data_proposta
     end
      
       @apolice.page = "proposta"

       respond_to do |format|
       if @apolice.save
           coberturas = Cobertura.all
         
           coberturas.each do |item|
             coberturaapolice = Coberturaapolice.new
             coberturaapolice.apolice_id = @apolice.id
             coberturaapolice.cobertura_id = item.id
             coberturaapolice.valor = item.valor
             coberturaapolice.valor_franquia = item.valor_franquia
             coberturaapolice.save
           end 
           format.html { redirect_to edit_proposta_path(@apolice), notice: 'Cadastro realizado com sucesso.' }
           format.json { render :show, status: :created, location: @apolice }
         else
           format.html { render :new }
           format.json { render json: @apolice.errors, status: :unprocessable_entity }
         end
       end
  end

  def showproposta

    @id = params[:id]
    @apolice = Apolice.find(@id)
    @url = "http://localhost:3000/relatorioproposta.pdf?id=#{@id}"
  
  end

  # GET /apolices/1/edit
  def edit
    @apolice.data_proposta = @apolice.data_proposta.strftime("%d/%m/%Y") rescue nil
    @apolice.vig_inicio = @apolice.vig_inicio.strftime("%d/%m/%Y") rescue nil
    @apolice.vig_termino = @apolice.vig_termino.strftime("%d/%m/%Y") rescue nil
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_apolice
    @apolice = Apolice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def apolice_params
    params.require(:apolice).permit(:ramo, :produto, :apolice, :item, :data_proposta, :vig_inicio, :vig_termino, :nome_segurado, :cpf, :endereco, :cidade, :bairro, :cep, :uf, :valr_premioliquido, :valr_adicional, :valr_custo, :valr_iof, :valr_premiototal, :desc_obs, :numr_mensal, :cnpj, :apartamento, :page, :valor_franquiaportao, :valor_mensal, :qtde_parcelas, :data_propostaaceita)
  end

end

app/helpers/proposta_helper.rb
module PropostaHelper
end

app/views/propostas/_form.html.erb
<%= form_for(@apolice) do |f| %>
  <% if @apolice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apolice.errors.count, "error") %> prohibited this apolice from being saved:</h2>

      <ul>
      <% @apolice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-lg-3">
     <%= f.label :ramo%><br>
     <%= f.text_field :ramo, :class => "form-control" %>
   </div>
  <div class="col-lg-2">
    <%= f.label :data_proposta %><br>
    <%= f.text_field :data_proposta, :class => "form-control"  %>
   </div>
   <div class="col-lg-2">
    <%= f.label :valor_mensal %><br>
    <%= f.text_field :valor_mensal, :class => "form-control"  %>
   </div>
    <div class="col-lg-2">
    <label>Quantidade de parcelas</label>
    <%= f.text_field :qtd_parcelas, :class => "form-control"  %>
   </div>
  </div>

<div class="row">
  <div class="col-lg-2">
    <%= f.label :vig_inicio %><br>
    <%= f.text_field :vig_inicio, :class => "form-control"  %>
  </div>
  <div class="col-lg-2">
    <%= f.label :vig_termino %><br>
    <%= f.text_field :vig_termino, :class => "form-control"  %>
  </div>
  <div class="col-lg-2">
   <label>N° Sorteio Mensal</label>
    <%= f.text_field :numr_mensal, :class => "form-control"  %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= f.label :nome_segurado %><br>
    <%= f.text_field :nome_segurado, :class => "form-control"  %>

  </div>
  <div class="col-lg-1">
    <div class="radio">
     <label><input type="radio" onclick="selecionar('CPF')" id="radiocpf" checked name="optradio">CPF</label>
    </div>
    <div class="radio">
     <label><input type="radio" onclick="selecionar('CNPJ')" id="radiocnpj" name="optradio">CNPJ</label>
    </div>
    <%= f.hidden_field :cnpj %>
 </div>
  <div class="col-lg-3">
   <label id="cpf">CPF</label>
   <label id="cnpj">CNPJ</label>
    <%= f.text_field :cpf, :class => "form-control"  %>
  </div>
</div>
<div class="row">
  <div class="col-lg-7">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco, :class => "form-control" %>
  </div>
  <div class="col-lg-2">
    <%= f.label :apartamento %><br>
    <%= f.text_field :apartamento, :class => "form-control" %>
  </div>
  <div class="col-lg-3">
    <%= f.label :bairro %><br>
    <%= f.text_field :bairro, :class => "form-control" %>
  </div>
</div>
<div class="row">
  <div class="col-lg-4">
    <%= f.label :cidade %><br>
    <%= f.text_field :cidade, :class => "form-control" %>
  </div>
  <div class="col-lg-2">
    <label>CEP</label>
    <%= f.text_field :cep, :class => "form-control" %>
  </div>
  <div class="col-lg-2">
    <label>UF</label>
    <%= f.text_field :uf, :class => "form-control" %>
  </div>
</div>

<div class="row">
  <div class="col-lg-2">
    <label>Prêmio líquido</label>
    <%= f.text_field :valr_premioliquido, :class => "form-control" %>
  </div>
  <div class="col-lg-2">
    <label>Sonar Assistencia</label>
    <%= f.text_field :valr_adicional, :class => "form-control" %>
  </div>

  <div class="col-lg-2">
    <label>Ad. de Fracionamento</label>
    <%= f.text_field :valr_custo, :class => "form-control" %>
  </div>
  <div class="col-lg-2">
    <label>IOF</label>
    <%= f.text_field :valr_iof, :class => "form-control" %>
  </div>
  <div class="col-lg-2">
    <label>Prêmio Total</label>
    <%= f.text_field :valr_premiototal, :class => "form-control" %>
  </div>
</div>

  <div class="row">
    <div class="col-lg-12">
      <label>Observações</label>
      <%= f.text_area :desc_obs, :class => "form-control" %>
    </div>
  </div>

  <hr>

  <%if @apolice.id%>
  <div class="row">
    <div class="col-lg-10">
      <select class="form-control" name="servico" id="servico">
        <option value="Chaveiro">Chaveiro</option>
        <option value="Hidráulica">Hidráulica</option>
        <option value="Eletrícista">Eletrícista</option>
        <option value="Vidraceiro">Vidraceiro</option>
        <option value="Desentupimento">Desentupimento</option>
        <option value="Chuveiro">Chuveiro</option>
        <option value="RC-Familiar">RC-Familiar</option>
      </select>
    </div>
    <div class="col-lg-2">
      <button type="button" class="btn btn-default" onclick="salva()">
        <span class="glyphicon glyphicon-arrow-down text-primary"></span> Adicionar
         </button>
    </div>
  </div>

  <br>
  <table class="table table-bordered">
      <thead>
        <tr>
          <th>Serviços utilizados</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="tbservico">
      </tbody>
    </table>

  <hr>

  <div class="row">
    <div class="col-lg-10">
      <select class="form-control" name="cobertura" id="cobertura">
        <% Cobertura.all.each do |item| %>
          <option value="<%=item.id%>"><%=item.nome%></option>
        <%end%>
      </select>
    </div>
    <div class="col-lg-2">
      <button type="button" class="btn btn-default" onclick="addCobertura()">
        <span class="glyphicon glyphicon-arrow-down text-primary"></span> Adicionar
         </button>
    </div>
  </div>


   <div class="panel panel-default">
    <div class="panel-heading">Coberturas</div>
    <div class="panel-body">
        
        <table class="table table-bordered">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Valor</th>
          <th>Franquia</th>
          <th></th>
        </tr>
      </thead>
       <tbody id="tbcoberturas">
       </tbody>
    </table>

     </div>
    </div>

    </div>
   </div>

 <% end %>

<div class="row mar-bot40">
<div class="col-lg-8" >
 <div class="btn-group">
    <button type="submit" value="Submit" class="btn btn-primary btn-sm">
    <span class="glyphicon glyphicon-floppy-disk"></span> Salvar
    </button>
    <%= link_to apolices_path, :class => "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-arrow-left"></span> Voltar
      <% end %>
  </div>
  </div>
 </div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">

    <input type="hidden" name="cobertura_id" id="cobertura_id">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Alterar Cobertura</h4>
      </div>
      <div class="modal-body">
       <div class="row">
         <div class='col-lg-12'>
           Valor 
            <input type='text' id='valor' name='valor' class='form-control'>
         </div>
        </div>
        <div class="row">
        <br>
        <div class='col-lg-12'>
           Valor franquia
           <input type='text' id='valor_franquia' name='valor_franquia' class='form-control'>
        </div>
       </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" onclick="salvaCobertura()" data-dismiss="modal">Salvar</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
    </div>

  </div>
</div>


 <% end %>

<script type="text/javascript">
function modalCobertura(item){
  
  $("#cobertura_id").val(item.id);
  $("#valor").val(item.valor);
  $("#valor_franquia").val(item.valor_franquia);
  $("#myModal").modal()
}
//função salvar/editar dados despesas
 function salva(){
      $.ajax({
        url: '/addservico',
        data : {
            servico:  $('#servico').val(),
            apolice_id: '<%=@apolice.id%>'
        },
        success: function(data){
          buscaServicos();
        }
      })
  };
 function addCobertura(){
      $.ajax({
        url: '/addcobertura',
        data : {
            cobertura_id:  $('#cobertura').val(),
            apolice_id: '<%=@apolice.id%>'
        },
        success: function(data){
          buscaCoberturas();
        }
      })
  };
function buscaServicos() {
  $.ajax({
    url: '/buscaservico',
    data : {
        apolice_id: '<%=@apolice.id%>'
    },
    success: function(data){
          var html = "";
          $("#tbservico").empty();
           for (var i in data) {
             var item = data[i];
             html += "<tr><td>"+item.nome+"</td>";
             html += "<td Align='center'>";
             html += " <button type='button' onclick='deleta_servico("+item.id+")' data-toggle='tooltip' title='Excluir' class='btn btn-danger btn-xs' aria-label='Left Align'>";
             html += "  <span class='glyphicon glyphicon-trash' aria-hidden='true'></span></button></tr>";
           };
           $("#tbservico").append(html);
         }
     })
  }
  //função salvar/editar dados despesas
function deleta_servico(id){
        $.ajax({
          url: '/deletaservico',
          data : {
              servico_id:  id
          },
          success: function(data){
            buscaServicos();
          }
        })
  };
http://localhost:3000/coberturas_apolice?apolice_id=16
function buscaCoberturas() {
  $.ajax({
    url: '/coberturas_apolice',
    data : {
      apolice_id: '<%=@apolice.id%>'
    },
    success: function(data){
          var html = "";
          $("#tbcoberturas").empty();
           for (var i in data) {
             var item = data[i];
             console.log(i);
             if(item != null){
              html += "<tr><td>"+item.nome+"</td>";
              html += "<td>"+item.valor+"</td>";
              html += "<td>"+item.valor_franquia+"</td>";
              html += "<td Align='center'>";
              html += " <button type='button' onclick='modalCobertura("+JSON.stringify(item)+")' data-toggle='tooltip' title='Excluir' class='btn btn-primary btn-xs' aria-label='Left Align'>";
              html += " <span class='glyphicon glyphicon-pencil' aria-hidden='true'></span></button>";
              html += " <button type='button' onclick='delete_cobertura("+item.id+")' data-toggle='tooltip' title='Excluir' class='btn btn-danger btn-xs' aria-label='Left Align'>";
              html += "  <span class='glyphicon glyphicon-trash' aria-hidden='true'></span></button></td></tr>";
             
             }
             
           }; 
           $("#tbcoberturas").append(html);        
         }
     })
  }
function salvaCobertura(){
    $.ajax({
        url: '/alteracobertura',
        data : {
            id:  $("#cobertura_id").val(),
            valor: $("#valor").val(),
            valor_franquia: $("#valor_franquia").val(),
        },
        success: function(data){
          buscaCoberturas();
        }
   })
}
function delete_cobertura(id){
    $.ajax({
        url: '/deletecobertura',
        data : {
            id:  id
        },
        success: function(data){
          buscaCoberturas();
        }
   })
}
function selecionar(val) {
  if (val == "CPF"){
      $("#cpf").show();
      $("#cnpj").hide();
      $("#apolice_cnpj").val(false);
      $("#apolice_cpf").mask("999.999.999-99");
  }
  if (val == "CNPJ"){
      $("#cnpj").show();
      $("#cpf").hide();
      $("#apolice_cnpj").val(true);
      $("#apolice_cpf").mask("99.999.999/9999-99");
  }
}
jQuery(function($){
  $("#cnpj").hide();
  $("#apolice_data_proposta").mask("99/99/9999");
  $("#apolice_vig_inicio").mask("99/99/9999");
  $("#apolice_vig_termino").mask("99/99/9999");
  var x = $("#apolice_cnpj").val();
   if(x){
        $("#apolice_cpf").mask("99.999.999/9999-99");
          $("#radiocnpj").attr("checked",true);
          $("#apolice_cnpj").val(true);
     }else{
        $("#apolice_cpf").mask("999.999.999-99");
        $("#radiocpf").attr("checked",true);
        $("#apolice_cnpj").val(false);
    }
});
$(function() {
   $("#apolice_valr_premioliquido").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   $("#apolice_valr_adicional").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   $("#apolice_valr_custo").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   $("#apolice_valr_iof").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   $("#apolice_valr_premiototal").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
  
   $("#valor").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   $("#valor_franquia").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   $("#apolice_valor_mensal").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
   
})
buscaServicos();
buscaCoberturas();
</script>

app/views/propostas/edit.html.erb
<br>
<div class="panel panel-default">
  <div class="panel-heading">Cadastro de Proposta</div>
  <div class="panel-body">
  <%= render 'form' %>

app/views/propostas/index.html.erb
<br>

<p id="notice"><%= notice %></p>

<%= form_tag nil, method: 'GET' do %>
  <div class="row">
    <div class="col-lg-12">
      <div class="input-group">
        <input id="q" name="q" type="text" value="<%=@q%>" class="form-control" placeholder="Pesquise pelo nome ou apartamento">
        <span class="input-group-btn">
          <button class="btn btn-success" type="submit" >Buscar</button>
        </span>
      </div>
    </div>
  </div>
  <br />

<% end %>
<div class="panel panel-default">
  <div class="panel-heading">Lista de Propostas</div>
  <div class="panel-body">
    <table class="table table-hover table-condensed">
      <thead>
        <tr>

          <th>Nome segurado</th>
          <th>N° Apolice</th>
          <th>CPF</th>
          <th>Prêmio liquido</th>
          <th>Adicional</th>
          <th>Custo</th>
          <th>IOF</th>
          <th>Prêmio Total</th>
          <th>Situação</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @apolices.each do |apolice| %>
          <tr>
            <td><%= apolice.nome_segurado %></td>
            <td><%= apolice.apolice %></td>
            <td><%= apolice.cpf %></td>
            <td><%= apolice.valr_premioliquido %></td>
            <td><%= apolice.valr_adicional %></td>
            <td><%= apolice.valr_custo %></td>
            <td><%= apolice.valr_iof %></td>
            <td><%= apolice.valr_premiototal %></td>
            <td>
               <%=  apolice.flag_propostaaceita == true ? "Aceita" : "Não aceita" %>                 
             </td>
            <td align='right'>
              <div class="btn-group">
                 <%= link_to new_proposta_path(id: apolice.id), class: "btn btn-default btn-sm" do %>
                    <span class="glyphicon glyphicon-transfer text-primary"></span>
                  <% end %>
                  <%= link_to edit_proposta_path(apolice), class: "btn btn-default btn-sm" do %>
                    <span class="glyphicon glyphicon-pencil text-primary"></span>
                  <% end %>
                 <%= link_to apolice, method: :delete, data: { confirm: 'Deseja excluir o registro?' }, class: "btn btn-default btn-sm" do %>
                    <span class="glyphicon glyphicon-trash text-danger"></span>
                  <% end %>
                  <%= link_to relatorioproposta_path(id: apolice, format: :pdf), class: "btn btn-default btn-sm" do %>
                    <span class="glyphicon glyphicon-print"></span> 1°
                  <% end %>
                  <button type="button" class="btn btn-default btn-sm" data-toggle="modal" onclick="copiar('<%=apolice.id%>')" data-target="#smallModal">Link</button>
              </div>
             </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= paginate @apolices, :window => 2 %>

<br>
<%= link_to new_proposta_path, class: "btn btn-default btn-sm" do %>
       <span class="glyphicon glyphicon-file"></span>Novo
<% end %>


<div class="modal fade" id="smallModal" tabindex="-1" role="dialog" aria-labelledby="smallModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Link para enviar proposta</h4>
      </div>
      <div class="modal-body">
        <h4 id="link">https://mapfre.herokuapp.com/visualizarproposta?id=<span id="idSpan"></span></h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>


<script>
 function copiar(id) {

    $("#idSpan").text(id);
    //var url = 'https://mapfre.herokuapp.com/visualizarproposta?id=' + id;
    //document.getElementById("#link").select();
    //$("#link").clone()
    //document.execCommand('copy');

    
 
 }
</script>

app/views/propostas/new.html.erb
<br>

<div class="panel panel-default">
  <div class="panel-heading">Cadastro de Proposta</div>
  <div class="panel-body">
     <%= render 'form' %>

app/views/propostas/showproposta.html.erb
<script>
 $("#menu").hide();
</script>

<br>

<div id="conteudo">
    <div class="jumbotron">
        <h3>Autorização</h3>
        <h5>Autorizo ao débito de 12 parcelas mensais na minha taxa condominial conforme proposta</h5>
        <button type="button" class="btn btn-default" aria-label="Left Align">
            Para autorizar o débito clique aqui
        </button>

        <hr>
        <div style="width:100%;height:600;overflow:hidden;">
        <iframe src="<%=@url%>" height="600" width="99%"></iframe>
        </div>
    </div>
</div>


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">

    <input type="hidden" name="cobertura_id" id="cobertura_id">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Identificação</h4>
      </div>
      <div class="modal-body">

        <div class="col-lg-12">
          <div class="radio">
          <label><input type="radio" onclick="selecionar('CPF')" id="radiocpf" checked name="optradio">CPF</label>
          </div>
          <div class="radio">
          <label><input type="radio" onclick="selecionar('CNPJ')" id="radiocnpj" name="optradio">CNPJ</label>
          </div>
      </div>

       <div class="row">
         <div class='col-lg-12'>
            CPF/CPF 
            <input type='text' id='cpf' name='cpf' class='form-control'>
         </div>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" onclick="validacao()" data-dismiss="modal">Acessar</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
    </div>

  </div>
</div>



<script>
  
$(function() {

  $("#myModal").modal();
  $("#conteudo").hide();
  $("#cpf").mask("999.999.999-99");
})

function validacao (){
    var cpf = '<%=@apolice.cpf%>';
    if($("#cpf").val() == cpf){
        $("#conteudo").show();
    }else{
        $("#conteudo").hide();
    }
}

</script>